# Generated by Django 5.1.4 on 2024-12-12 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_image', models.ImageField(upload_to='media/ministries')),
                ('team_description', models.TextField()),
                ('team_chair', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='media/events')),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
                ('event_venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiritual_year', models.CharField(max_length=50)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='media/execs')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=100)),
                ('ministry_image', models.ImageField(upload_to='media/ministries')),
                ('ministry_description', models.TextField()),
                ('ministry_chair', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_giver', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/testimonies')),
                ('position', models.CharField(max_length=100)),
                ('testimony', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=150)),
                ('leader_image', models.ImageField(upload_to='media/leaders')),
                ('leader_position', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Vice Secretary', 'Vice Secretary'), ('Organizing Secretary', 'Organizing Secretary'), ('Librarian', 'Librarian'), ('Missions Coordinator', 'Missions Coordinator'), ('Bible Study Coordinator', 'Bible Study Coordinator'), ('Technical Coordinator', 'Technical Coordinator'), ('Music Director', 'Music Director'), ('Prayer Secretary', 'Prayer Secretary')], max_length=150)),
                ('leader_description', models.TextField()),
                ('leader_contact', models.CharField(max_length=50)),
                ('exec_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.exec')),
            ],
        ),
    ]
