# Generated by Django 5.1.4 on 2024-12-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'ministries'},
        ),
    ]
