# Generated by Django 5.1.4 on 2025-01-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='home_county',
            new_name='homeCounty',
        ),
    ]
