# Generated by Django 5.1.4 on 2024-12-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_book_alter_testimony_options_userinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
