# Generated by Django 5.1.4 on 2024-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_userinteraction_book_delete_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/gallery')),
                ('image_category', models.CharField(choices=[('event', 'event'), ('service', 'service'), ('fellowship', 'fellowship'), ('outdoors', 'outdoors')], max_length=50)),
            ],
        ),
    ]
