# Generated by Django 5.1.4 on 2024-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_eteam_team_image_alter_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eteam',
            name='team_image',
            field=models.ImageField(upload_to='media/ministries'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='media/events'),
        ),
        migrations.AlterField(
            model_name='exec',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/execs'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/gallery'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leader_image',
            field=models.ImageField(upload_to='media/leaders'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='ministry_image',
            field=models.ImageField(upload_to='media/ministries'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(upload_to='media/testimonies'),
        ),
    ]
