# Generated by Django 5.1.4 on 2024-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_eteam_team_image_alter_event_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_to_show_on_website',
            field=models.BooleanField(default=True),
        ),
    ]
